<script src="{{ asset('frontend/assets/js/jquery-3.6.0.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script src="{{ asset('frontend/assets/js/wow.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/jquery.slick.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/swiper.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/moment.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/daterangepicker.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/lightgallery.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/YTPlayer.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/main.js') }}"></script>
